# Generated by Django 5.2.5 on 2026-05-17 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dim_company',
            },
        ),
        migrations.CreateModel(
            name='FactAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('sales_growth', models.FloatField(null=True)),
                ('profit_growth', models.FloatField(null=True)),
                ('stock_cagr', models.FloatField(null=True)),
                ('roe_clean', models.FloatField(null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='companies.dimcompany')),
            ],
            options={
                'db_table': 'fact_analysis',
            },
        ),
        migrations.CreateModel(
            name='FactBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.FloatField(null=True)),
                ('total_liabilities', models.FloatField(null=True)),
                ('debt_to_equity', models.FloatField(null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='companies.dimcompany')),
            ],
            options={
                'db_table': 'fact_balance_sheet',
            },
        ),
        migrations.CreateModel(
            name='FactCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_cash_flow', models.FloatField(null=True)),
                ('free_cash_flow', models.FloatField(null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='companies.dimcompany')),
            ],
            options={
                'db_table': 'fact_cash_flow',
            },
        ),
    ]
