# Generated by Django 5.2.5 on 2026-05-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factanalysis',
            name='id',
        ),
        migrations.AlterField(
            model_name='factanalysis',
            name='period',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
